# FRP C/S 长连接
serverAddr = "" # 你的 FRPS IP
serverPort = 7000 # FRPS bindPort

# 服务代理列表
[[proxies]]
name = "mc-server"
type = "tcp"
localIP = "mc-server"
localPort = {{ .Envs.MC_SERVER_PORT }} # 本机 mc-server 端口
remotePort = {{ .Envs.REMOTE_MC_SERVER_PORT }} # mc-server 的 FRPS 远程端口

[[proxies]]
name = "mc-rcon"
type = "tcp"
localIP = "mc-server"
localPort = {{ .Envs.MC_RCON_PORT }} # 本机 RCON 端口
remotePort = {{ .Envs.REMOTE_MC_RCON_PORT }} # mc-server 的 FRPS 远程端口

# TODO: 完成 Grafana 监控的 frpc http 配置
# [[proxies]]
# name = "mc-grafana"
# type = "http"
# localIP = "mc-server"
# localPort = {{ .Envs.GF_SERVER_HTTP_PORT }} # 本机 mc-grafana 端口
# vhostHTTPPort = {{ .Envs.REMOTE_GF_SERVER_HTTP_PORT }} # mc-grafana 的 FRPS 远程端口