global:
  scrape_interval: 10s

scrape_configs:
  # [______ Cadvisor Docker 监控 ______]
  - job_name: mc-cadvisor
    static_configs:
    - targets: ['mc-cadvisor:8888']
    metrics_path: /metrics
    scrape_interval: 20s
    scrape_timeout: 10s

  # [______ MC Monitor 指标 ______]
  - job_name: mc-monitor
    static_configs:
    - targets: ['mc-monitor:8889']
    metrics_path: /metrics
    scrape_interval: 20s
    scrape_timeout: 10s
