x-FABRIC:
  environment: &FABRIC_ENV
    MC_VERSION: ${MC_VERSION:?'[fabric.yml][mc-server] No MC_VERSION set.'}

    TYPE: "FABRIC"
    FABRIC_LOADER_VERSION: "${FABRIC_LOADER_VERSION:?'[fabric.yml][mc-server] No FABRIC_LOADER_VERSION set.'}"
    FABRIC_LAUNCHER_VERSION: "${FABRIC_LAUNCHER_VERSION:?'[fabric.yml][mc-server] No FABRIC_LAUNCHER_VERSION set.'}"
services:
  # ______ Minecraft Server ______
  mc-server:
    environment:
      <<: *FABRIC_ENV
