x-FORGE:
  environment: &FORGE_ENV
    MC_VERSION: ${MC_VERSION:?'[forge.yml][mc-server] No MC_VERSION set.'}
    TYPE: "FORGE"
    FORGE_VERSION: "${FORGE_VERSION:?'[forge.yml][mc-server] No FORGE_VERSION set.'}"

services:
  # ______ Minecraft Server ______
  mc-server:
    environment:
      <<: *FORGE_ENV
