x-NEOFORGE:
  environment: &NEOFORGE_ENV
    MC_VERSION: ${MC_VERSION:?'[neoforge.yml][mc-server] No MC_VERSION set.'}
    TYPE: "NEOFORGE"
    NEOFORGE_VERSION: "${NEOFORGE_VERSION:?'[neoforge.yml][mc-server] No NEOFORGE_VERSION set.'}"

services:
  # ______ Minecraft Server ______
  mc-server:
    environment:
      <<: *NEOFORGE_ENV
