services:
  mc-frpc:
    # [______ MC FRP Client ______]
    image: snowdreamtech/frpc:latest
    container_name: mc-frpc
    restart: unless-stopped
    command: ["frpc", "-c", "/etc/frp/frpc.toml"]
    volumes:
      - ./resources/config/frpc/frpc.toml:/etc/frp/frpc.toml
    environment:
      MC_SERVER_PORT: ${MC_SERVER_PORT}
      MC_RCON_PORT: ${MC_RCON_PORT}
      GF_SERVER_HTTP_PORT: ${GF_SERVER_HTTP_PORT}
      REMOTE_MC_SERVER_PORT: ${REMOTE_MC_SERVER_PORT}
      REMOTE_MC_RCON_PORT: ${REMOTE_MC_RCON_PORT}
      REMOTE_GF_SERVER_HTTP_PORT: ${REMOTE_GF_SERVER_HTTP_PORT}
    networks:
      mc-network:
        aliases:
          - mc-frpc