# FRP C/S 长连接
serverAddr: "" # 你的 FRPS IP
serverPort: 7000 # FRPS bindPort

# 服务代理列表
proxies:
  # 配置 MC Server 流量透传
  - name: "mc-server"
    type: "tcp"
    localIP: "localhost"
    localPort: ${MC_SERVER_PORT:?'[frpc][mc-server] 未设置 MC_SERVER_PORT.'}  # 本机 mc-server 端口
    remotePort: ${REMOTE_MC_SERVER_PORT:?'[frpc][mc-server] 未设置 REMOTE_MC_SERVER_PORT.'} # mc-server 的 FRPS 远程端口

  - name: "mc-rcon"
    type: "tcp"
    localIP: "localhost"
    localPort: ${MC_RCON_PORT:?'[frpc][mc-rcon] 未设置 MC_RCON_PORT.'} # 本机 RCON 端口
    remotePort: ${REMOTE_MC_RCON_PORT:?'[frpc][mc-server] 未设置 REMOTE_MC_RCON_PORT.'} # mc-server 的 FRPS 远程端口

  - name: "mc-grfana"
    type: "http"
    localIP: "localhost"
    localPort: ${GF_SERVER_HTTP_PORT} # 本机 mc-grafana 端口
    remotePort: ${REMOTE_GF_SERVER_HTTP_PORT:?'[frpc][mc-grfana] 未设置 REMOTE_GF_SERVER_HTTP_PORT.'} # mc-grafana 的 FRPS 远程端口